#!/usr/bin/env bash
# Sync AGENTS.md (canonical SoT) to per-tool mirror files.
#
# Mirrors get a hidden HTML banner so any AI agent or human opening them
# knows the file is auto-generated. Markdown rendering hides the banner;
# raw-text consumers (LLMs, grep) see it.
#
# Usage:
#   scripts/sync-harness-mirrors.sh           # sync all
#   scripts/sync-harness-mirrors.sh --check   # exit 1 if any mirror diverges (CI/pre-commit)
#
# Standard: AAIF / agents.md (https://agents.md/)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SOURCE="$REPO_ROOT/AGENTS.md"
MIRRORS=(CLAUDE.md GEMINI.md OPENCODE.md CODEX.md)
MODE="${1:-sync}"

if [[ ! -f "$SOURCE" ]]; then
  echo "error: $SOURCE not found" >&2
  exit 1
fi

# Build mirror content = banner + AGENTS.md
make_mirror() {
  local mirror_name="$1"
  cat <<EOF
<!--
⚠️  AUTO-GENERATED MIRROR of AGENTS.md.
Do not edit this file directly. Edit AGENTS.md and run:
  scripts/sync-harness-mirrors.sh

This mirror exists so $mirror_name-aware tools (which read this filename
preferentially) get the same Single Source of Truth as AGENTS.md.

Standard: AAIF / agents.md (https://agents.md/)
-->

EOF
  cat "$SOURCE"
}

if [[ "$MODE" == "--check" ]]; then
  diverged=0
  for m in "${MIRRORS[@]}"; do
    expected=$(make_mirror "$m")
    actual=$(cat "$REPO_ROOT/$m" 2>/dev/null || true)
    if [[ "$expected" != "$actual" ]]; then
      echo "diverged: $m"
      diverged=1
    fi
  done
  if [[ $diverged -eq 1 ]]; then
    echo "error: one or more mirrors diverged from AGENTS.md. Run scripts/sync-harness-mirrors.sh." >&2
    exit 1
  fi
  echo "ok: all mirrors in sync with AGENTS.md"
  exit 0
fi

# Sync mode
for m in "${MIRRORS[@]}"; do
  make_mirror "$m" > "$REPO_ROOT/$m"
  echo "synced: $m  ←  AGENTS.md"
done

echo
echo "✓ ${#MIRRORS[@]} mirrors synced from AGENTS.md"
echo "  Mirrors: ${MIRRORS[*]}"
echo
echo "Tip: install pre-commit hook to auto-sync:"
echo "  ln -sf ../../scripts/sync-harness-mirrors.sh .git/hooks/pre-commit"
